export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";

export const GET_CATEGORIES_BY_LEVEL_REQUEST = "GET_CATEGORIES_BY_LEVEL_REQUEST";
export const GET_CATEGORIES_BY_LEVEL_SUCCESS = "GET_CATEGORIES_BY_LEVEL_SUCCESS";
export const GET_CATEGORIES_BY_LEVEL_FAILURE = "GET_CATEGORIES_BY_LEVEL_FAILURE";

export const GET_CATEGORIES_BY_PARENT_REQUEST = "GET_CATEGORIES_BY_PARENT_REQUEST";
export const GET_CATEGORIES_BY_PARENT_SUCCESS = "GET_CATEGORIES_BY_PARENT_SUCCESS";
export const GET_CATEGORIES_BY_PARENT_FAILURE = "GET_CATEGORIES_BY_PARENT_FAILURE";

export const INITIALIZE_CATEGORIES_REQUEST = "INITIALIZE_CATEGORIES_REQUEST";
export const INITIALIZE_CATEGORIES_SUCCESS = "INITIALIZE_CATEGORIES_SUCCESS";
export const INITIALIZE_CATEGORIES_FAILURE = "INITIALIZE_CATEGORIES_FAILURE";
