export const GET_DASHBOARD_ANALYTICS_REQUEST = "GET_DASHBOARD_ANALYTICS_REQUEST";
export const GET_DASHBOARD_ANALYTICS_SUCCESS = "GET_DASHBOARD_ANALYTICS_SUCCESS";
export const GET_DASHBOARD_ANALYTICS_FAILURE = "GET_DASHBOARD_ANALYTICS_FAILURE";
